audit_header: false
title: Brea Real Estate Video Blog with Jon Long
description: Our mission at Ardent Real Estate Group, Inc. is to be your best resource for Brea real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Ardent Real Estate Group, Inc., your professional Brea Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jon Long
  title:
  license_number: CA DRE# 01850579
  about_markdown: |
    Jon Long’s name is well known in the Brea real estate market and surrounding areas, where his well established reputation and unmatched market knowledge have made him a frontrunner in Brea California’s residential real estate industry. As the broker and owner of Ardent Real Estate Group Inc. with sales volumes of over $30 Million dollars in the past 3 years, Jon prides himself on his personal service and attention to his clients’ every detail, which has led him to a large base of referral and repeating clients. Jon brings nearly a decade of experience to every transaction, where he specializes in Orange and Los Angeles County communities from Whittier to Irvine and out-land to Newport Beach. Jon’s past clients have made him a 5 star rated Realtor® on both Zillow and Yelp due to his expansive network, unparalleled client service, and proven marketing strategies.
  brand: Ardent Real Estate Group, Inc.
  brokerage:
  market: Brea
  address: 3230 East Imperial Hwy Suite 130, Brea, CA 92821
  phone: 714-396-6848
  phone_type:
  phone2:
  phone2_type:
  email: jon@ardentreg.com
  url: https://www.ardentrealestategroup.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.ardentrealestategroup.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.ardentrealestategroup.com/results-map

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Brea Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.ardentrealestategroup.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Brea Home?"
    CTA_text2: "Search the entire MLS for your Brea home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.ardentrealestategroup.com/results-map

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ardentreg
  linkedin_url: https://www.linkedin.com/in/ardentreg
  youtube_url: https://www.youtube.com/user/ardentrealestate
  twitter_url: https://twitter.com/ardentreg
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/JonLong87/
  trulia_url:
  yelp_url: https://www.yelp.com/biz/jon-long-ardent-real-estate-group-brea
  podcast_url:

podcast:
  title: 'Brea Real Estate Podcast with Jon Long'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Brea Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Ardent Real Estate Group, Inc. - your professional Brea Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Brea, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jon Long'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Brea Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#005596'
  theme_color: '#333333'
  accent_color: '#C4960C'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
